### ISSUE TITLE
批量处理crash脚本

### ISSUE THREAD

**Issue by xinali** [xinali/articles#50]
```python3
#encoding:utf-8

import sys
import glob
import subprocess
import os
import datetime

# 调试器位置
cdb = "C:\\Program Files (x86)\\Windows Kits\\10\Debuggers\\x64\\cdb.exe"
gdb = "/usr/bin/gdb"


# 结果存储文件
debugger_result_file = 'resoult_crash_{}.txt'.format((datetime.datetime.now()).strftime("%Y-%m-%d"))
uniq_crash_type_file = 'uniq_crash_type_{}.txt'.format((datetime.datetime.now()).strftime("%Y-%m-%d"))

debugger = None
if sys.platform == 'win32':
    debugger = cdb
if sys.platform == 'linux':
    debugger = gdb


def usage():
    usage_info = \
    """
====================================================
python: 3.5+
处理fuzz crash脚本
执行： python3 fuzz_program crash_directory
产生两个文件: 
    resoult_crash_YYYY-mm-dd.txt    => 所有的debugger结果
    uniq_crash_type_YYYY-mm-dd.txt  => 所有crash type结果

type是根据call stack 最后两个调用函数划分
====================================================
    """
    print(usage_info)


# 根据调用栈最后两个函数判定类型 (Windows)
def get_crash_type_win32(stdout):
     # 获取到crash type
    i = 0
    stdout_split = stdout.decode().split('\n')
    stdout_line_data = None
    for crash_data in stdout_split:
        if "RetAddr" in crash_data:
            break
        i += 1
    
    if i == len(stdout_split):
        return None

    # 得出最后两个调用栈作为划分类型
    if len(stdout_split) > i and len(stdout_split[i].split(' ')) > 3:
        stdout_line_data = stdout_split[i].split(' ')[2]
    if len(stdout_split) > i+1 and len(stdout_split[i+1].split(' ')) > 3:
        stdout_line_data += ' -> ' + stdout_split[i+1].split(' ')[2]
    return stdout_line_data


# 根据调用栈最后两个函数判定类型 (linux)
def get_crash_type_linux(stdout):
    # 获取到crash type
    i = 0
    stdout_split = stdout.decode().split('\n')
    stdout_line_data = None
    for crash_data in stdout_split:
        if "#" in crash_data:
            break
        i += 1
    
    # 主动过滤前两个，目前遇到的情况是，前两个用处不大
    i += 2
    if len(stdout_split) > i and len(stdout_split[i].split(' ')) > 4:
        stdout_line_data = stdout_split[i].split(' ')[4]
    if len(stdout_split) > i+1 and len(stdout_split[i+1].split(' ')) > 4:
        stdout_line_data += ' -> ' + stdout_split[i+1].split(' ')[4]
    return stdout_line_data

# 将crash_types写入文件
def handle_crash_types(crash_types):
    fp = open(uniq_crash_type_file, 'w')
    for crash_type in crash_types:
        fp.write(crash_type + ':\n')
        for crash_file in crash_types[crash_type]:
            fp.write("   [+] {}\n".format(crash_file))
    fp.close()


def main(argvs):
    if len(argvs) < 3:
        usage()
        exit(1)
    
    fuzz_program = argvs[1]
    crash_directory = argvs[2]

    if debugger == None:
        print("未知平台,目前仅支持windows和linux")
        exit(3)
    
    if not os.path.isfile(fuzz_program):
        print("%s 非文件" % fuzz_program)
        usage()
        exit(4)
    
    if not os.path.isdir(crash_directory):
        print("%s 非目录" % crash_directory)
        usage()
        exit(5)

    files = []
    # 获取所有crash/hangs文件
    if debugger == cdb:
        files.extend(glob.glob(crash_directory + '\\*\\crashes*\\*', recursive=True))
        files.extend(glob.glob(crash_directory + '\\*\\hangs*\\*', recursive=True))
    if debugger == gdb:
        # 单级目录
        files.extend(glob.glob(crash_directory + '/crashes*/*', recursive=True))
        files.extend(glob.glob(crash_directory + '/hangs*/*', recursive=True))
        # 多级目录
        files.extend(glob.glob(crash_directory + '/*/crashes*/*', recursive=True))
        files.extend(glob.glob(crash_directory + '/*/hangs*/*', recursive=True))

    if len(files) == 0:
        usage()
        exit(6)

    open(debugger_result_file, 'wb').close()
    crash_types = {}
    for crash_file in files:
        print('handling ' + crash_file)
        fp = open(debugger_result_file, 'ab+')

        stdout = None
        stderr = None
        crash_type = None
        # 处理windows
        if debugger == cdb:
            command = [debugger, 
                        "-y", 
                        "srv*c:\symbols*https://msdl.microsoft.com/download/symbols", 
                        "-c", 
                        "g;kp 10;q",
                        fuzz_program,
                        crash_file]

            process_out = subprocess.Popen(command, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
            stdout, stderr = process_out.communicate(process_out)
            crash_type = get_crash_type_win32(stdout)
            if crash_type not in crash_types.keys():
                crash_types[crash_type] = [crash_file]
            elif crash_type != None:
                crash_types[crash_type].append(crash_file)

        if debugger == gdb:
            command =  [debugger, 
                        "--batch", 
                        "-q", 
                        "--ex", 
                        "r '{}'".format(crash_file),
                        "--ex",
                        "bt", 
                        "--ex",
                        "quit",
                        fuzz_program]
            process_out = subprocess.Popen(command, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
            stdout, stderr = process_out.communicate()

            # 无调用栈的情况不处理
            if 'No stack' in stdout.decode():
                continue
            
            crash_type = get_crash_type_linux(stdout)
            if crash_type not in crash_types.keys():
                crash_types[crash_type] = [crash_file]
            else:
                crash_types[crash_type].append(crash_file)
        
        fp.write(stdout)
        fp.close()

    handle_crash_types(crash_types)
    

if __name__ == "__main__":
    main(sys.argv)
```

大致结果
`uniq_crash_type_xxx`

```
_IO_vsscanf -> __sscanf:
   [+] output/crashes/id:000003,sig:11,src:000000,op:havoc,rep:128
   [+] output/crashes/id:000006,sig:11,src:000001,op:havoc,rep:128
   [+] output/crashes/id:000004,sig:11,src:000000,op:havoc,rep:32
   [+] output/crashes/id:000003,sig:11,src:000000,op:havoc,rep:128.0.jp2
   [+] output/crashes/id:000005,sig:11,src:000001,op:havoc,rep:16
   [+] output/crashes/id:000000,sig:11,src:000000,op:flip1,pos:4199
   [+] output/crashes/id:000002,sig:11,src:000000,op:ext_AO,pos:12552
__assert_fail_base -> __GI___assert_fail:
   [+] output/crashes/id:000001,sig:06,src:000000,op:ext_AO,pos:0
   [+] output/crashes/id:000007,sig:06,src:000003,op:ext_AO,pos:0
```

`result_crash_xxx`

```
Program received signal SIGSEGV, Segmentation fault.
rawmemchr () at ../sysdeps/x86_64/rawmemchr.S:37
37	../sysdeps/x86_64/rawmemchr.S: No such file or directory.
#0  rawmemchr () at ../sysdeps/x86_64/rawmemchr.S:37
#1  0x00007ffff7a89ff2 in _IO_str_init_static_internal (sf=sf@entry=0x7fffffffcab0, ptr=ptr@entry=0x0, size=size@entry=0, pstart=pstart@entry=0x0) at strops.c:41
#2  0x00007ffff7a7d267 in _IO_vsscanf (string=0x0, format=0x401c60 "/Length  %d/", args=args@entry=0x7fffffffcbd8) at iovsscanf.c:40
#3  0x00007ffff7a77917 in __sscanf (s=<optimized out>, format=format@entry=0x401c60 "/Length  %d/") at sscanf.c:32
#4  0x00000000004010eb in main (argc=<optimized out>, argv=<optimized out>) at pdf2jp2.c:114
A debugging session is active.

	Inferior 1 [process 147901] will be killed.

Quit anyway? (y or n) [answered Y; input not from terminal]

Program received signal SIGSEGV, Segmentation fault.
rawmemchr () at ../sysdeps/x86_64/rawmemchr.S:37
37	../sysdeps/x86_64/rawmemchr.S: No such file or directory.
#0  rawmemchr () at ../sysdeps/x86_64/rawmemchr.S:37
#1  0x00007ffff7a89ff2 in _IO_str_init_static_internal (sf=sf@entry=0x7fffffffcab0, ptr=ptr@entry=0x0, size=size@entry=0, pstart=pstart@entry=0x0) at strops.c:41
#2  0x00007ffff7a7d267 in _IO_vsscanf (string=0x0, format=0x401c60 "/Length  %d/", args=args@entry=0x7fffffffcbd8) at iovsscanf.c:40
#3  0x00007ffff7a77917 in __sscanf (s=<optimized out>, format=format@entry=0x401c60 "/Length  %d/") at sscanf.c:32
#4  0x00000000004010eb in main (argc=<optimized out>, argv=<optimized out>) at pdf2jp2.c:114
A debugging session is active.

	Inferior 1 [process 149330] will be killed.

Quit anyway? (y or n) [answered Y; input not from terminal]

Program received signal SIGSEGV, Segmentation fault.
rawmemchr () at ../sysdeps/x86_64/rawmemchr.S:37
37	../sysdeps/x86_64/rawmemchr.S: No such file or directory.
#0  rawmemchr () at ../sysdeps/x86_64/rawmemchr.S:37
#1  0x00007ffff7a89ff2 in _IO_str_init_static_internal (sf=sf@entry=0x7fffffffcab0, ptr=ptr@entry=0x0, size=size@entry=0, pstart=pstart@entry=0x0) at strops.c:41
#2  0x00007ffff7a7d267 in _IO_vsscanf (string=0x0, format=0x401c60 "/Length  %d/", args=args@entry=0x7fffffffcbd8) at iovsscanf.c:40
#3  0x00007ffff7a77917 in __sscanf (s=<optimized out>, format=format@entry=0x401c60 "/Length  %d/") at sscanf.c:32
#4  0x00000000004010eb in main (argc=<optimized out>, argv=<optimized out>) at pdf2jp2.c:114
A debugging session is active.

	Inferior 1 [process 152058] will be killed.

Quit anyway? (y or n) [answered Y; input not from terminal]

Program received signal SIGSEGV, Segmentation fault.
rawmemchr () at ../sysdeps/x86_64/rawmemchr.S:37
37	../sysdeps/x86_64/rawmemchr.S: No such file or directory.
#0  rawmemchr () at ../sysdeps/x86_64/rawmemchr.S:37
#1  0x00007ffff7a89ff2 in _IO_str_init_static_internal (sf=sf@entry=0x7fffffffcaa0, ptr=ptr@entry=0x0, size=size@entry=0, pstart=pstart@entry=0x0) at strops.c:41
#2  0x00007ffff7a7d267 in _IO_vsscanf (string=0x0, format=0x401c60 "/Length  %d/", args=args@entry=0x7fffffffcbc8) at iovsscanf.c:40
#3  0x00007ffff7a77917 in __sscanf (s=<optimized out>, format=format@entry=0x401c60 "/Length  %d/") at sscanf.c:32
#4  0x00000000004010eb in main (argc=<optimized out>, argv=<optimized out>) at pdf2jp2.c:114
A debugging session is active.

	Inferior 1 [process 154816] will be killed.

Quit anyway? (y or n) [answered Y; input not from terminal]
pdf2jp2: pdf2jp2.c:109: main: Assertion `ret == 0' failed.

Program received signal SIGABRT, Aborted.
0x00007ffff7a42428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
54	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
#0  0x00007ffff7a42428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007ffff7a4402a in __GI_abort () at abort.c:89
#2  0x00007ffff7a3abd7 in __assert_fail_base (fmt=<optimized out>, assertion=assertion@entry=0x401c55 "ret == 0", file=file@entry=0x401c37 "pdf2jp2.c", line=line@entry=109, function=function@entry=0x401cc8 <__PRETTY_FUNCTION__.3100> "main") at assert.c:92
#3  0x00007ffff7a3ac82 in __GI___assert_fail (assertion=assertion@entry=0x401c55 "ret == 0", file=file@entry=0x401c37 "pdf2jp2.c", line=line@entry=109, function=function@entry=0x401cc8 <__PRETTY_FUNCTION__.3100> "main") at assert.c:101
#4  0x00000000004015d5 in main (argc=<optimized out>, argv=<optimized out>) at pdf2jp2.c:109
A debugging session is active.

	Inferior 1 [process 156299] will be killed.

Quit anyway? (y or n) [answered Y; input not from terminal]
pdf2jp2: pdf2jp2.c:109: main: Assertion `ret == 0' failed.

Program received signal SIGABRT, Aborted.
0x00007ffff7a42428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
54	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
#0  0x00007ffff7a42428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007ffff7a4402a in __GI_abort () at abort.c:89
#2  0x00007ffff7a3abd7 in __assert_fail_base (fmt=<optimized out>, assertion=assertion@entry=0x401c55 "ret == 0", file=file@entry=0x401c37 "pdf2jp2.c", line=line@entry=109, function=function@entry=0x401cc8 <__PRETTY_FUNCTION__.3100> "main") at assert.c:92
#3  0x00007ffff7a3ac82 in __GI___assert_fail (assertion=assertion@entry=0x401c55 "ret == 0", file=file@entry=0x401c37 "pdf2jp2.c", line=line@entry=109, function=function@entry=0x401cc8 <__PRETTY_FUNCTION__.3100> "main") at assert.c:101
#4  0x00000000004015d5 in main (argc=<optimized out>, argv=<optimized out>) at pdf2jp2.c:109
A debugging session is active.

	Inferior 1 [process 157781] will be killed.

Quit anyway? (y or n) [answered Y; input not from terminal]

Program received signal SIGSEGV, Segmentation fault.
rawmemchr () at ../sysdeps/x86_64/rawmemchr.S:37
37	../sysdeps/x86_64/rawmemchr.S: No such file or directory.
#0  rawmemchr () at ../sysdeps/x86_64/rawmemchr.S:37
#1  0x00007ffff7a89ff2 in _IO_str_init_static_internal (sf=sf@entry=0x7fffffffcab0, ptr=ptr@entry=0x0, size=size@entry=0, pstart=pstart@entry=0x0) at strops.c:41
#2  0x00007ffff7a7d267 in _IO_vsscanf (string=0x0, format=0x401c60 "/Length  %d/", args=args@entry=0x7fffffffcbd8) at iovsscanf.c:40
#3  0x00007ffff7a77917 in __sscanf (s=<optimized out>, format=format@entry=0x401c60 "/Length  %d/") at sscanf.c:32
#4  0x00000000004010eb in main (argc=<optimized out>, argv=<optimized out>) at pdf2jp2.c:114
A debugging session is active.

	Inferior 1 [process 160393] will be killed.

Quit anyway? (y or n) [answered Y; input not from terminal]

Program received signal SIGSEGV, Segmentation fault.
rawmemchr () at ../sysdeps/x86_64/rawmemchr.S:37
37	../sysdeps/x86_64/rawmemchr.S: No such file or directory.
#0  rawmemchr () at ../sysdeps/x86_64/rawmemchr.S:37
#1  0x00007ffff7a89ff2 in _IO_str_init_static_internal (sf=sf@entry=0x7fffffffcab0, ptr=ptr@entry=0x0, size=size@entry=0, pstart=pstart@entry=0x0) at strops.c:41
#2  0x00007ffff7a7d267 in _IO_vsscanf (string=0x0, format=0x401c60 "/Length  %d/", args=args@entry=0x7fffffffcbd8) at iovsscanf.c:40
#3  0x00007ffff7a77917 in __sscanf (s=<optimized out>, format=format@entry=0x401c60 "/Length  %d/") at sscanf.c:32
#4  0x00000000004010eb in main (argc=<optimized out>, argv=<optimized out>) at pdf2jp2.c:114
A debugging session is active.

	Inferior 1 [process 163191] will be killed.

Quit anyway? (y or n) [answered Y; input not from terminal]

Program received signal SIGSEGV, Segmentation fault.
rawmemchr () at ../sysdeps/x86_64/rawmemchr.S:37
37	../sysdeps/x86_64/rawmemchr.S: No such file or directory.
#0  rawmemchr () at ../sysdeps/x86_64/rawmemchr.S:37
#1  0x00007ffff7a89ff2 in _IO_str_init_static_internal (sf=sf@entry=0x7fffffffcaa0, ptr=ptr@entry=0x0, size=size@entry=0, pstart=pstart@entry=0x0) at strops.c:41
#2  0x00007ffff7a7d267 in _IO_vsscanf (string=0x0, format=0x401c60 "/Length  %d/", args=args@entry=0x7fffffffcbc8) at iovsscanf.c:40
#3  0x00007ffff7a77917 in __sscanf (s=<optimized out>, format=format@entry=0x401c60 "/Length  %d/") at sscanf.c:32
#4  0x00000000004010eb in main (argc=<optimized out>, argv=<optimized out>) at pdf2jp2.c:114
A debugging session is active.

	Inferior 1 [process 164607] will be killed.

Quit anyway? (y or n) [answered Y; input not from terminal]
```

整个处理流程还在优化中，遇到特殊的crash结果，会及时更新

**Comment by xinali** [comment]
`20200528` 添加BugId批量处理

**Comment by xinali** [comment]
`20200623` 添加libfuzzer crash处理

**Comment by xinali** [comment]
`20200710` 添加选项将crash_file写入指定文件进行debug

**Comment by xinali** [comment]
`20211228` 删除`linux`相关支持，目前仅支持`windows`，并优化多个崩溃处理逻辑
